site_name: Zero to Mastery Kubernetes
site_url: https://www.learnpytorch.io
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/JamorMoussa/k8s
repo_name: JamorMoussa/k8s

theme:
  name: material
  logo: 
  favicon: 
  features:
    - navigation.instant
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: black
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

nav:
  - Home: 'index.md'
  - Get Started: 'started.md'

# extra:
#   social:
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/mrdbourke
#     - icon: fontawesome/brands/github
#       link: https://github.com/mrdbourke/pytorch-deep-learning
#     - icon: fontawesome/brands/youtube
#       link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ